### ISSUE TITLE
Version compare error

### ISSUE THREAD

**Issue by sspreitzer** [timorunge/ansible-sssd#5]
Hi Timo

We would like to use your SSSD module at the Paul Scherrer Institute. We are using AWX/Ansible Tower to invoke your module. However we run into a problem in your version compare.

https://github.com/timorunge/ansible-sssd/blob/29f0c8b51e9ab0c34fe161412befd0a0e6f5f0cf/tasks/install-pkgs.yml#L7

The error is;
```
TASK [timorunge.sssd : Install SSSD packages] **********************************
fatal: [rhel-8-client-2.psi.ch]: FAILED! => {"msg": "Version comparison: '<' not supported between instances of 'str' and 'int'"}
```

Hope you can help.

Thank you
Sascha

**Comment by sspreitzer** [comment]
The Ansible version Ansible Tower/AWX uses is 2.9.5

**Comment by sspreitzer** [comment]
Maybe related to https://github.com/ansible/ansible/issues/35435

**Comment by sspreitzer** [comment]
Possible solution https://github.com/plone/ansible-playbook/blob/2ecf0e5f86fc4616c23bfc7635ed1da35dc81e4e/playbook.yml#L13

**Comment by timorunge** [comment]
@sspreitzer, which version of Python are you using? Even if 2.7 is EOL soon please give it a try.

**Comment by sspreitzer** [comment]
Afaik latest awx uses Python3 in version 3.6

**Comment by sspreitzer** [comment]
See #6
